create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.uploaded_movies (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  genre text not null,
  release_year integer,
  duration text default 'Streaming',
  rating numeric(3,1) default 0,
  maturity text default '13+',
  video_path text not null,
  video_url text not null,
  poster_path text,
  poster_url text,
  backdrop_path text,
  backdrop_url text,
  is_published boolean not null default true,
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv')),
  tmdb_id integer not null,
  created_at timestamptz not null default now(),
  unique (user_id, media_type, tmdb_id)
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv')),
  tmdb_id integer not null,
  created_at timestamptz not null default now(),
  unique (user_id, media_type, tmdb_id)
);

create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv')),
  tmdb_id integer not null,
  progress_seconds integer not null default 0,
  watched_at timestamptz not null default now(),
  unique (user_id, media_type, tmdb_id)
);

alter table public.profiles enable row level security;
alter table public.watchlist enable row level security;
alter table public.favorites enable row level security;
alter table public.watch_history enable row level security;
alter table public.uploaded_movies enable row level security;

alter table public.watchlist alter column tmdb_id drop not null;
alter table public.favorites alter column tmdb_id drop not null;
alter table public.watch_history alter column tmdb_id drop not null;

alter table public.watchlist add column if not exists uploaded_movie_id uuid references public.uploaded_movies(id) on delete cascade;
alter table public.favorites add column if not exists uploaded_movie_id uuid references public.uploaded_movies(id) on delete cascade;
alter table public.watch_history add column if not exists uploaded_movie_id uuid references public.uploaded_movies(id) on delete cascade;

create unique index if not exists watchlist_uploaded_movie_unique
on public.watchlist (user_id, uploaded_movie_id)
where uploaded_movie_id is not null;

create unique index if not exists favorites_uploaded_movie_unique
on public.favorites (user_id, uploaded_movie_id)
where uploaded_movie_id is not null;

create unique index if not exists watch_history_uploaded_movie_unique
on public.watch_history (user_id, uploaded_movie_id)
where uploaded_movie_id is not null;

create policy "Profiles are readable by owner"
on public.profiles for select
using (auth.uid() = id);

create policy "Profiles are insertable by owner"
on public.profiles for insert
with check (auth.uid() = id);

create policy "Profiles are updatable by owner"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Watchlist owner access"
on public.watchlist for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Favorites owner access"
on public.favorites for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "History owner access"
on public.watch_history for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Published uploaded movies are readable"
on public.uploaded_movies for select
using (is_published = true);

create policy "Admins can manage uploaded movies"
on public.uploaded_movies for all
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

insert into storage.buckets (id, name, public)
values ('movie-videos', 'movie-videos', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('movie-images', 'movie-images', true)
on conflict (id) do nothing;

create policy "Public can stream movie videos"
on storage.objects for select
using (bucket_id = 'movie-videos');

create policy "Public can view movie images"
on storage.objects for select
using (bucket_id = 'movie-images');

create policy "Admins can upload movie videos"
on storage.objects for insert
with check (
  bucket_id = 'movie-videos'
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

create policy "Admins can upload movie images"
on storage.objects for insert
with check (
  bucket_id = 'movie-images'
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

create policy "Admins can update movie storage"
on storage.objects for update
using (
  bucket_id in ('movie-videos', 'movie-images')
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);
